# content.py

def get_intro_text():
    return """
### What is a Monte Carlo Simulation?
Monte Carlo simulations are a mathematical technique used to estimate the possible outcomes of an uncertain event. By running a scenario (like a coin toss or a project schedule) hundreds or thousands of times with random variables, we can see the full range of possibilities and their probabilities.

### Key Concepts in Simulations
*   **Trials vs. Repeats:** A **trial** is one single event (e.g., flipping one coin). A **repeat** (or iteration) is running a set of trials to get one result. In our app, we repeat a set of trials many times to build a distribution.
*   **Law of Large Numbers:** This theorem states that as the number of trials increases, the average of the results gets closer to the expected (theoretical) value. More trials mean a smoother, more predictable bell curve.
*   **Noise:** When you run the same simulation twice with a small number of trials, the results will look different. This variation is called 'noise'. Increasing the number of trials reduces noise.
*   **Sample Set:** The total collection of data points generated by our simulation repeats. We use this sample to estimate the behavior of the entire system.
    """

def get_definitions():
    return """
### Statistical Definitions

*   **Mean (μ):** The mathematical average of all results. In a normal distribution, it sits at the exact center of the curve.
*   **Median:** The middle value when all results are sorted from lowest to highest.
*   **Mode:** The most frequently occurring result in the dataset.
*   **Normal Distribution (Bell Curve):** A probability distribution that is symmetric about the mean, showing that data near the mean are more frequent in occurrence than data far from the mean.
*   **Standard Deviation (σ):** A measure of the amount of variation or dispersion of a set of values. A low standard deviation indicates that the values tend to be close to the mean.

#### Theoretical Probabilities (Empirical Rule)
For a perfectly normal distribution:
*   **1 Standard Deviation (1σ):** Contains ~**68.27%** of all outcomes.
*   **2 Standard Deviations (2σ):** Contains ~**95.45%** of all outcomes.
*   **3 Standard Deviations (3σ):** Contains ~**99.73%** of all outcomes.
*   **6 Standard Deviations (6σ):** Represents a defect rate of 3.4 per million opportunities. It means almost 100% of outcomes fall within this range.
    """

def get_sidebar_info():
    return "Configure your simulation parameters below. Try changing the number of trials to observe the Law of Large Numbers in action!"

def get_real_world_examples():
    return """
### 🌍 Real-World Applications of Monte Carlo

Monte Carlo simulations are heavily relied upon across multiple industries to model risk, uncertainty, and complex systems where straightforward mathematical calculations are impossible due to the sheer number of variables.

#### 1. Project Management (Risk & Schedules)
* **The Problem:** In large construction or IT projects, thousands of tasks depend on one another. If one task is delayed by weather, resource shortages, or bugs, how does that ripple through the rest of the project?
* **The Simulation:** A Monte Carlo simulation takes the estimated duration of every single task (e.g., Task A takes between 5 and 15 days) and runs the entire project schedule thousands of times.
* **The Result:** Instead of giving a single, unrealistic completion date, the simulation outputs a probability curve. It allows project managers to say: *"We have an 80% confidence level (P80) that the project will finish by November 15th, but only a 10% chance it finishes by October 1st."* This helps in setting realistic client expectations and allocating contingency budgets.

#### 2. Insurance (Claim Risk Modelling)
* **The Problem:** Insurance companies need to make sure they have enough cash reserves to pay out claims in extreme scenarios (like a massive hurricane hitting a major city) without going bankrupt. 
* **The Simulation:** They model thousands of hypothetical years, randomly generating disaster events based on historical weather patterns, fault line activity, and property density data.
* **The Result:** The simulation creates a distribution of possible financial losses for the year. This helps the insurer calculate the "Value at Risk" (VaR) to determine exactly how much capital they must legally hold in reserve, and how they should price their premiums to remain profitable over the long term.

#### 3. Finance (Stock Market & Options Pricing)
* **The Problem:** Predicting the future price of a stock or pricing a complex derivative (like a stock option) is incredibly difficult because markets are driven by random daily fluctuations (volatility).
* **The Simulation:** Quantitative analysts use Monte Carlo methods (often based on Geometric Brownian Motion) to simulate tens of thousands of possible future price paths for a stock over a given time period.
* **The Result:** By averaging the payoff of an option across all these thousands of simulated future paths, traders can determine the mathematically "fair" price of that option today. It is also used to stress-test entire investment portfolios against hypothetical market crashes.

#### 4. Fraud Detection & Cybersecurity
* **The Problem:** Identifying fraudulent credit card transactions or network intrusions requires separating normal behavior from malicious anomalies in massive datasets.
* **The Simulation:** Companies simulate typical user behavior (login times, transaction locations, purchase amounts) thousands of times to establish a baseline probability distribution of "normal" activity.
* **The Result:** When a live transaction occurs, it is compared against this simulated baseline. If the probability of that specific transaction happening naturally is extremely low (e.g., falling in the extreme 99.9th percentile tail of the curve), the system automatically flags it as high-risk fraud and blocks the card.
    """